# Generated by Django 5.2.6 on 2025-10-01 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tab', models.CharField(choices=[('nacional', 'Nacional'), ('local', 'Local'), ('soporte', 'Soporte')], default='nacional', max_length=10)),
                ('text', models.TextField()),
                ('avatar', models.CharField(blank=True, max_length=255)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
