# Generated by assistant
from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('chatApp', '0002_product_cartitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='sender',
            field=models.CharField(max_length=150, null=True, blank=True),
        ),
    ]
