# Generated by Django 5.2.5 on 2025-10-17 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatApp', '0003_add_sender_to_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='badge',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='caracteristicas',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='product',
            name='es_destacado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='tipo',
            field=models.CharField(choices=[('individual', 'Software El Almacén - Punto de Venta 1 PC'), ('red', 'Software El Almacén en Red para 2 o 3 PC'), ('empresarial', 'Software El Almacén Empresarial Multi PC')], default='individual', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='precio',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
