<<<<<<< HEAD
# Generated by Django 5.2.6 on 2025-10-17 05:54
=======
# Generated by Django 5.2.5 on 2025-10-17 05:46
>>>>>>> cbadb7078b4a8d08bf3a95f0ecd2517e1d6faa57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatApp', '0005_add_initial_products'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='badge',
        ),
        migrations.RemoveField(
            model_name='product',
            name='caracteristicas',
        ),
        migrations.RemoveField(
            model_name='product',
            name='es_destacado',
        ),
        migrations.RemoveField(
            model_name='product',
            name='tipo',
        ),
        migrations.AlterField(
            model_name='product',
            name='precio',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
