# Generated by Django 5.2.6 on 2025-11-03 01:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatApp', '0006_remove_product_badge_remove_product_caracteristicas_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_completo', models.CharField(blank=True, max_length=200)),
                ('telefono', models.CharField(blank=True, max_length=20)),
                ('whatsapp', models.CharField(blank=True, max_length=20)),
                ('relacion_negocio', models.CharField(blank=True, choices=[('dueno', 'Dueño'), ('conyuge', 'Cónyuge'), ('hijo', 'Hijo/a'), ('trabajador', 'Trabajador')], max_length=50)),
                ('tipo_negocio', models.CharField(blank=True, choices=[('almacen', 'Almacén'), ('minimarket', 'Minimarket'), ('botilleria', 'Botillería'), ('panaderia', 'Panadería'), ('ferreteria', 'Ferretería'), ('farmacia', 'Farmacia'), ('bazar', 'Bazar'), ('otro', 'Otro')], max_length=50)),
                ('nombre_negocio', models.CharField(blank=True, max_length=200)),
                ('comuna', models.CharField(blank=True, max_length=100)),
                ('region', models.CharField(blank=True, max_length=100)),
                ('direccion', models.CharField(blank=True, max_length=300)),
                ('foto_perfil', models.ImageField(blank=True, null=True, upload_to='profiles/')),
                ('recibir_notificaciones', models.BooleanField(default=True)),
                ('recibir_newsletter', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Perfil de Usuario',
                'verbose_name_plural': 'Perfiles de Usuarios',
            },
        ),
    ]
