# Generated by Django 5.2.6 on 2025-11-22 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatApp', '0007_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('user', 'Usuario'), ('admin', 'Administrador')], default='user', max_length=20),
        ),
    ]
