# Generated by Django 5.2.6 on 2025-11-23 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatApp', '0010_tag_comment_blogpost_tags_reaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='blog/videos/'),
        ),
    ]
